name: MSBuild

on:
  push:
    branches: [ "workshop" ]
    paths-ignore:
      - '*.txt'
      - '*.lua'
      - '*.md'
  pull_request:
    branches: [ "workshop" ]
  workflow_dispatch:
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Setup cmake project
      run: cmake -B build -G "Visual Studio 17 2022" -A win32

    - name: Build
      working-directory: build
      run: msbuild ALL_BUILD.vcxproj -p:Configuration=Release
    
    - name: Get Result
      working-directory: build
      run: mkdir output && copy Release\inject.dll output\inject.bin && copy Release\patcher.exe output\patcher.exe && copy Release\patcher_rgon.exe output\patcher_rgon.exe
    
    - name: Attest
      if: github.event_name == 'workflow_dispatch'
      uses: actions/attest@v4
      with:
        subject-path: 'build/output'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: build/output
